---
- name: Deploy Application Stack
  hosts: webservers
  become: true

  tasks:
    - name: Deploy TREK app
      include_tasks:
        file: tasks/setup-trek.yml

    # - name: Deploy LibreChat app
    #   include_tasks:
    #     file: tasks/setup-librechat.yml

    - name: Deploy Typesense app
      include_tasks:
        file: tasks/setup-typesense.yml

    - name: Deploy Actual Budget app
      include_tasks:
        file: tasks/setup-actual.yml

    - name: Deploy Actual MCP server
      include_tasks:
        file: tasks/setup-actual-mcp.yml

    - name: Deploy SillyTavern app
      include_tasks:
        file: tasks/setup-sillytavern.yml
