---
- name: Centralize Caddy Proxy
  hosts: webservers
  become: true

  handlers:
    - name: reload caddy
      command: >
        docker exec caddy_proxy caddy reload --config /etc/caddy/Caddyfile

  tasks:
    - name: Ensure /opt/caddy directory exists
      file:
        path: /opt/caddy
        state: directory
        mode: '0755'

    - name: Copy Caddy docker-compose file
      copy:
        src: files/docker-compose.caddy.yml
        dest: /opt/caddy/docker-compose.yml

    - name: Ensure the shared external overlay network exists
      docker_network:
        name: webnet
        state: present
        driver: bridge

    - name: Template the master Caddyfile
      template:
        src: templates/Caddyfile.j2
        dest: /opt/caddy/Caddyfile
      notify: reload caddy

    - name: Ensure Caddy container is running
      community.docker.docker_compose_v2:
        project_src: /opt/caddy
        state: present
        pull: always
